fileName: /shared/home/croux/data/Morpho_Peru_dils.fa
binpath: /shared/ifbstor1/home/croux/scratch/morpho/DILS_3pop_SNP/bin 
config_yaml: /shared/ifbstor1/home/croux/scratch/morpho/DILS_3pop_SNP/analysis/config.yaml
mail_address: camille.roux@univ-lille.fr
timeStamp: testMorpho
nspecies: 3
nameA: hel_P
nameB: ach_P
nameC: dei_P
nameOut: NA
region: noncoding
Lmin: 100
max_N_tolerated: 0.1
nMinA: 20
nMinB: 26
nMinC: 16
Nref: 100000
mu: 0.000000003
rho_over_theta: 0.1
Nmin: 200
Nmax: 700000
Tmin: 0
Tmax: 8000000
Mmin: 2
Mmax: 50
shapeMin: 0.01
shapeMax: 20
fixed_Na: True

